## Pravila pridruživanja na skupu podataka `market.csv`

**a)** Primeniti algoritam apriori sa minimalnom podrškom od 20\% i minimalnom pouzdanošću 50\%.

**b)** Koliko pravila je ukupno pronađeno?

**c)** Koliko pravila je interesantno po lift meri?

**d)** Koliko ima pravila u kojima je u zaključku sir ('Cheese')? Izdvojiti sva takva u pravila u poseban model.

**e)** Da li je bilo potrebno podeliti podatke na trening i test skup? Da li je bilo potrebno dodatno pretprocesiranje podataka? Zašto?

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('market.csv', sep=';')
df.head()

,Bread,Honey,Bacon,Toothpaste,Banana,Apple,Hazelnut,Cheese,Meat,Carrot,...,Milk,Butter,ShavingFoam,Salt,Flour,HeavyCream,Egg,Olive,Shampoo,Sugar
0,1,0,1,0,1,1,1,0,0,1,...,0,0,0,0,0,1,1,0,0,1
1,1,1,1,0,1,1,1,0,0,0,...,1,1,0,0,1,0,0,1,1,0
2,0,1,1,1,1,1,1,1,1,0,...,1,0,1,1,1,1,1,0,0,1
3,1,1,0,1,0,1,0,0,0,0,...,1,0,0,0,1,0,1,1,1,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
transactions = [df.columns[row == 1].tolist() for _, row in df.iterrows()]
transactions[:3]

[['Bread',
  'Bacon',
  'Banana',
  'Apple',
  'Hazelnut',
  'Carrot',
  'HeavyCream',
  'Egg',
  'Sugar'],
 ['Bread',
  'Honey',
  'Bacon',
  'Banana',
  'Apple',
  'Hazelnut',
  'Cucumber',
  'Milk',
  'Butter',
  'Flour',
  'Olive',
  'Shampoo'],
 ['Honey',
  'Bacon',
  'Toothpaste',
  'Banana',
  'Apple',
  'Hazelnut',
  'Cheese',
  'Meat',
  'Cucumber',
  'Onion',
  'Milk',
  'ShavingFoam',
  'Salt',
  'Flour',
  'HeavyCream',
  'Egg',
  'Sugar']]

In [4]:
from apriori_python import apriori

In [5]:
freq_item, rules = apriori(transactions, minSup=0.2, minConf=0.5)

In [6]:
len(rules)

41

In [7]:
rules = pd.DataFrame(rules, columns=['Antecedent', 'Consequent', 'Confidence'])
rules

       Antecedent    Consequent  Confidence
0         {Honey}         {Egg}    0.502591
1    {HeavyCream}    {Hazelnut}    0.502591
2           {Egg}      {Carrot}    0.502674
3           {Egg}       {Bacon}    0.502674
4          {Salt}      {Cheese}    0.502703
5        {Cheese}       {Bacon}    0.504854
6        {Cheese}      {Banana}    0.504854
7         {Bread}        {Salt}    0.507937
8         {Honey}      {Banana}    0.512953
9         {Bacon}    {Hazelnut}    0.515000
10        {Bread}      {Banana}    0.518519
11          {Egg}       {Honey}    0.518717
12         {Salt}       {Bread}    0.518919
13         {Salt}  {HeavyCream}    0.518919
14        {Flour}    {Hazelnut}    0.519553
15        {Bacon}      {Cheese}    0.520000
16         {Meat}       {Honey}    0.522222
17        {Honey}      {Cheese}    0.523316
18       {Carrot}      {Cheese}    0.526042
19  {ShavingFoam}      {Cheese}    0.526596
20         {Meat}      {Cheese}    0.527778
21   {Toothpaste}      {Banana}    0.528090
22   {Toothpaste}    {Hazelnut}    0.528090
23     {Hazelnut}      {Banana}    0.528205
24     {Hazelnut}       {Bacon}    0.528205
25        {Bread}      {Cheese}    0.529101
26          {Egg}      {Banana}    0.529412
27       {Carrot}      {Banana}    0.531250
28  {ShavingFoam}       {Bacon}    0.531915
29   {Toothpaste}      {Carrot}    0.533708
30        {Olive}      {Banana}    0.536723
31       {Banana}       {Bacon}    0.538462
32  {ShavingFoam}      {Banana}    0.542553
33        {Apple}      {Banana}    0.542553
34          {Egg}      {Cheese}    0.550802
35        {Onion}      {Banana}    0.551136
36       {Butter}       {Bacon}    0.551724
37         {Meat}       {Bacon}    0.555556
38         {Milk}  {HeavyCream}    0.558140
39        {Bacon}      {Banana}    0.560000
40       {Butter}      {Cheese}    0.574713

In [8]:
def support(itemset, transactions):
    count = sum(itemset.issubset(t) for t in transactions)
    return count / len(transactions)

In [9]:
transactions = [set(t) for t in transactions]

In [10]:
rules['Lift'] = rules.apply(lambda row : row['Confidence'] / support(row['Consequent'], transactions), axis=1)

In [11]:
rules

       Antecedent    Consequent  Confidence      Lift
0         {Honey}         {Egg}    0.502591  1.247070
1    {HeavyCream}    {Hazelnut}    0.502591  1.195908
2           {Egg}      {Carrot}    0.502674  1.214795
3           {Egg}       {Bacon}    0.502674  1.166203
4          {Salt}      {Cheese}    0.502703  1.132301
5        {Cheese}       {Bacon}    0.504854  1.171262
6        {Cheese}      {Banana}    0.504854  1.126214
7         {Bread}        {Salt}    0.507937  1.273960
8         {Honey}      {Banana}    0.512953  1.144281
9         {Bacon}    {Hazelnut}    0.515000  1.225436
10        {Bread}      {Banana}    0.518519  1.156695
11          {Egg}       {Honey}    0.518717  1.247070
12         {Salt}       {Bread}    0.518919  1.273960
13         {Salt}  {HeavyCream}    0.518919  1.247556
14        {Flour}    {Hazelnut}    0.519553  1.236270
15        {Bacon}      {Cheese}    0.520000  1.171262
16         {Meat}       {Honey}    0.522222  1.255498
17        {Honey}      {Cheese}    0.523316  1.178731
18       {Carrot}      {Cheese}    0.526042  1.184871
19  {ShavingFoam}      {Cheese}    0.526596  1.186119
20         {Meat}      {Cheese}    0.527778  1.188781
21   {Toothpaste}      {Banana}    0.528090  1.178047
22   {Toothpaste}    {Hazelnut}    0.528090  1.256583
23     {Hazelnut}      {Banana}    0.528205  1.178304
24     {Hazelnut}       {Bacon}    0.528205  1.225436
25        {Bread}      {Cheese}    0.529101  1.191760
26          {Egg}      {Banana}    0.529412  1.180995
27       {Carrot}      {Banana}    0.531250  1.185096
28  {ShavingFoam}       {Bacon}    0.531915  1.234043
29   {Toothpaste}      {Carrot}    0.533708  1.289794
30        {Olive}      {Banana}    0.536723  1.197306
31       {Banana}       {Bacon}    0.538462  1.249231
32  {ShavingFoam}      {Banana}    0.542553  1.210311
33        {Apple}      {Banana}    0.542553  1.210311
34          {Egg}      {Cheese}    0.550802  1.240642
35        {Onion}      {Banana}    0.551136  1.229458
36       {Butter}       {Bacon}    0.551724  1.280000
37         {Meat}       {Bacon}    0.555556  1.288889
38         {Milk}  {HeavyCream}    0.558140  1.341848
39        {Bacon}      {Banana}    0.560000  1.249231
40       {Butter}      {Cheese}    0.574713  1.294498

In [15]:
rules['Lift'].min()

1.1262135922330097

Sva pravila su interesantna po lift meri jer je minimalni lift 1.13.

In [13]:
cheese_rules = rules[rules.apply(lambda row : {'Cheese'}.issubset(row['Consequent']), axis=1)]
cheese_rules

       Antecedent Consequent  Confidence      Lift
4          {Salt}   {Cheese}    0.502703  1.132301
15        {Bacon}   {Cheese}    0.520000  1.171262
17        {Honey}   {Cheese}    0.523316  1.178731
18       {Carrot}   {Cheese}    0.526042  1.184871
19  {ShavingFoam}   {Cheese}    0.526596  1.186119
20         {Meat}   {Cheese}    0.527778  1.188781
25        {Bread}   {Cheese}    0.529101  1.191760
34          {Egg}   {Cheese}    0.550802  1.240642
40       {Butter}   {Cheese}    0.574713  1.294498

In [14]:
len(cheese_rules)

9

Nije potrebno deliti podatke na trening i test skup, s obzirom na to da ne primenjujemo algoritam nadgledanog učenja. Pretprocesiranje je bilo potrebno samo kako bi se podaci iz učitanog formata pripremili u vidu liste transakcija koje očekuje apriori algoritam.